# Generated by Django 5.2.7 on 2025-12-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university_affiliation',
            field=models.CharField(blank=True, help_text='University or research institution (for researchers)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hospital_affiliation',
            field=models.CharField(blank=True, help_text='Hospital or lab name (for doctors and lab technicians)', max_length=200, null=True),
        ),
    ]
