# Generated by Django 5.2.7 on 2025-12-31 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_university_affiliation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Administrator"),
                    ("Doctor", "Doctor"),
                    ("Lab Technician", "Lab Technician"),
                    ("Researcher", "Researcher"),
                ],
                default="Lab Technician",
                help_text="User's role in the system",
                max_length=20,
            ),
        ),
    ]
