# Generated by Django 5.2.7 on 2026-03-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("gender", models.CharField(choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")], max_length=10)),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("emergency_contact", models.CharField(blank=True, max_length=150)),
                ("emergency_phone", models.CharField(blank=True, max_length=20)),
                ("medical_history", models.TextField(blank=True)),
                ("current_medications", models.TextField(blank=True)),
                ("symptoms", models.TextField(blank=True)),
                ("referring_doctor", models.CharField(blank=True, max_length=150)),
                ("suspected_disease", models.CharField(blank=True, max_length=150)),
                ("status", models.CharField(
                    choices=[("Pending", "Pending"), ("In Progress", "In Progress"), ("Diagnosed", "Diagnosed")],
                    default="Pending",
                    max_length=20,
                )),
                ("cbc_report", models.FileField(upload_to="patients/cbc_reports/%Y/%m/%d/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="BloodSmearImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="patients/blood_smear/%Y/%m/%d/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_smear_images",
                        to="analysis.patient",
                    ),
                ),
            ],
            options={"ordering": ["uploaded_at"]},
        ),
        migrations.CreateModel(
            name="PatientFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("results", models.JSONField(blank=True, default=list)),
                ("comment", models.TextField(blank=True)),
                ("decision", models.CharField(
                    choices=[("Accept Results", "Accept Results"), ("Re-Diagnosis", "Re-Diagnosis")],
                    max_length=30,
                )),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_entries",
                        to="analysis.patient",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_feedback_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cbc_data", models.JSONField(blank=True, default=dict)),
                ("results", models.JSONField(blank=True, default=dict)),
                ("models_used", models.JSONField(blank=True, default=list)),
                ("inference_errors", models.JSONField(blank=True, default=dict)),
                ("processing_time_ms", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(
                    choices=[("PENDING", "Pending"), ("COMPLETED", "Completed"), ("FAILED", "Failed")],
                    default="PENDING",
                    max_length=16,
                )),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
