# Generated by Django 5.2.7 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_patientfeedback"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="patientfeedback",
            constraint=models.UniqueConstraint(
                fields=("patient",),
                name="unique_feedback_per_patient",
            ),
        ),
    ]
