# Generated by Django 5.2.7 on 2026-03-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0004_patientfeedback_unique_per_patient"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="patientfeedback",
            name="unique_feedback_per_patient",
        ),
    ]
