# Generated by Django 6.0.3 on 2026-03-07 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_add_diagnosis_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisresult',
            name='analysis_method',
            field=models.CharField(choices=[('cbc_only', 'CBC Only'), ('hybrid', 'Hybrid')], default='cbc_only', max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='hybrid_analysis',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='image_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AnnotatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='patients/annotated/%Y/%m/%d/')),
                ('detections_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotated_images', to='analysis.diagnosisresult')),
            ],
        ),
    ]
