# -*- coding: utf-8 -*-
"""preprocessing_leukemia_yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/134gf7WIpcMWnQCnVN6tJmSqBlY3vPSk8
"""

import os
import shutil
import random
from PIL import ImageFile

ImageFile.LOAD_TRUNCATED_IMAGES = True

CLASSES = ["ALLNeg", "ALLPos"]

# -----------------------------
# STEP 1: Reorganize dataset
# -----------------------------
def prepare_binary_dataset(src_base, dest_base):
    main_folder = "Segmented"

    os.makedirs(dest_base, exist_ok=True)

    for cls in CLASSES:
        src_path = os.path.join(src_base, main_folder, cls)
        dst_path = os.path.join(dest_base, cls)
        os.makedirs(dst_path, exist_ok=True)

        for img in os.listdir(src_path):
            src = os.path.join(src_path, img)
            dst = os.path.join(dst_path, img)
            if not os.path.exists(dst):
                shutil.copy(src, dst)

    print("✅ Dataset reorganized")

# -----------------------------
# STEP 2: Train / Val / Test split
# -----------------------------
def prepare_dataset_splits(base_dir, train_ratio=0.7, val_ratio=0.15):
    splits = ["train", "val", "test"]

    for split in splits:
        for cls in CLASSES:
            os.makedirs(os.path.join(base_dir, split, cls), exist_ok=True)

    for cls in CLASSES:
        images = os.listdir(os.path.join(base_dir, cls))
        random.shuffle(images)

        n = len(images)
        t_end = int(train_ratio * n)
        v_end = int((train_ratio + val_ratio) * n)

        split_map = {
            "train": images[:t_end],
            "val": images[t_end:v_end],
            "test": images[v_end:]
        }

        for split, imgs in split_map.items():
            for img in imgs:
                shutil.copy(
                    os.path.join(base_dir, cls, img),
                    os.path.join(base_dir, split, cls, img)
                )

    print("✅ Train / Val / Test split completed")

# -----------------------------
# STEP 3: Wrapper
# -----------------------------
def preprocess_leukemia_yolo(input_path, output_path):
    prepare_binary_dataset(input_path, output_path)
    prepare_dataset_splits(output_path)