# -*- coding: utf-8 -*-
"""preprocessing_leukemia_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10B65OmFtXxIiYc5Dobwux08wEcw5bzXN
"""

# =============================
# Leukemia (ALL) Preprocessing
# =============================

import os
import shutil
import random
from PIL import Image, ImageFile
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Fix truncated image warnings
ImageFile.LOAD_TRUNCATED_IMAGES = True

# -----------------------------
# STEP 1: Reorganize dataset
# -----------------------------
def prepare_binary_dataset(src_base, dest_base):
    main_folder = 'Segmented'
    classes = ['ALLNeg', 'ALLPos']

    os.makedirs(dest_base, exist_ok=True)

    for cls in classes:
        src_path = os.path.join(src_base, main_folder, cls)
        dst_path = os.path.join(dest_base, cls)
        os.makedirs(dst_path, exist_ok=True)

        for img_name in os.listdir(src_path):
            src = os.path.join(src_path, img_name)
            dst = os.path.join(dst_path, img_name)
            if not os.path.exists(dst):  # avoid duplicates
                shutil.copy(src, dst)

    print("✅ Dataset reorganized into:", os.listdir(dest_base))

# -----------------------------
# STEP 2: Split Train / Val / Test
# -----------------------------
def prepare_dataset_splits(base_dir, train_ratio=0.7, val_ratio=0.15, test_ratio=0.15):
    assert abs(train_ratio + val_ratio + test_ratio - 1.0) < 1e-6, "Ratios must sum to 1"

    classes = ['ALLNeg', 'ALLPos']
    splits = ['train', 'val', 'test']

    for split in splits:
        for cls in classes:
            os.makedirs(os.path.join(base_dir, split, cls), exist_ok=True)

    for cls in classes:
        cls_dir = os.path.join(base_dir, cls)
        images = os.listdir(cls_dir)
        random.shuffle(images)

        total = len(images)
        train_end = int(train_ratio * total)
        val_end = int((train_ratio + val_ratio) * total)

        train_imgs = images[:train_end]
        val_imgs = images[train_end:val_end]
        test_imgs = images[val_end:]

        for split, img_list in zip(splits, [train_imgs, val_imgs, test_imgs]):
            for img_name in img_list:
                src = os.path.join(cls_dir, img_name)
                dst = os.path.join(base_dir, split, cls, img_name)
                shutil.copy(src, dst)

    print("✅ Data split into train / val / test folders.")

# -----------------------------
# STEP 3: Create Generators
# -----------------------------
def create_generators(base_dir, img_size=(128, 128), batch_size=32):
    train_datagen = ImageDataGenerator(
        rescale=1.0/255,
        rotation_range=20,
        width_shift_range=0.1,
        height_shift_range=0.1,
        shear_range=0.1,
        zoom_range=0.1,
        horizontal_flip=True,
        fill_mode='nearest'
    )

    test_val_datagen = ImageDataGenerator(rescale=1.0/255)

    train_gen = train_datagen.flow_from_directory(
        os.path.join(base_dir, 'train'),
        target_size=img_size,
        batch_size=batch_size,
        class_mode='binary'
    )

    val_gen = test_val_datagen.flow_from_directory(
        os.path.join(base_dir, 'val'),
        target_size=img_size,
        batch_size=batch_size,
        class_mode='binary'
    )

    test_gen = test_val_datagen.flow_from_directory(
        os.path.join(base_dir, 'test'),
        target_size=img_size,
        batch_size=batch_size,
        class_mode='binary',
        shuffle=False
    )

    print("✅ Generators ready.")
    return train_gen, val_gen, test_gen

# -----------------------------
# STEP 4: Wrap Everything
# -----------------------------
def preprocess_leukemia_dataset(input_path, output_path, img_size=(128, 128), batch_size=32):
    prepare_binary_dataset(input_path, output_path)
    prepare_dataset_splits(output_path)
    return create_generators(output_path, img_size, batch_size)